### PR TITLE
Update TTFB description

### PR DESCRIPTION
**Pull request by michellelychan**
Update TTFB description text when user hovers on TTFB.

### CODE REVIEW

**Review by jpvajda — COMMENTED** [review]
This looks a bit long as the text creates a pretty big hover tool tip so introducing a line break to put it 2 lines might be better @michellelychan 

Suggestion below 👇 

```js
<Tooltip
    showArrow
    className="p-5"
    content="Time to first byte (TTFB) is the time it takes from initiating an API request to receiving the first byte\nof audio from the response."
  >
    <span className="underline decoration-dotted">Time to first-byte</span>
  </Tooltip>
```
Screenshot 2024-03-08 at 6 02 43 PM

**Review by jpvajda — APPROVED** [review]

**Review by jpvajda — CHANGES_REQUESTED** [review]
Requesting changes

**Comment by michellelychan** [comment]
> This looks a bit long as the text creates a pretty big hover tool tip so introducing a line break to put it 2 lines might be better @michellelychan
> 
> Suggestion below 👇
> 
> ```js
> <Tooltip
>     showArrow
>     className="p-5"
>     content="Time to first byte (TTFB) is the time it takes from initiating an API request to receiving the first byte\nof audio from the response."
>   >
>     <span className="underline decoration-dotted">Time to first-byte</span>
>   </Tooltip>
> ```
> 
> Screenshot 2024-03-08 at 6 02 43 PM

I updated the tooltip in the latest commit. Your /n doesn't work it just shows /n and it will have unnecessary line breaks on mobile. I added some tailwind classes there.

**Comment by michellelychan** [comment]
I also changed the first sentence to make Asteria not miss the `d` in `today` and have a weird inflection at `Aura?` in the same pull request to save time.

**Review by jpvajda — APPROVED** [review]

**Pull request merged**
